config/routes.rb
Rails.application.routes.draw do
  resources :somethings do
    get :notify
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/something.rb
class Something < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def appear(on: nil)
    puts "User #{id} appeared on #{on} at #{Time.now}"
  end

  def away
    puts "User #{id} went away at #{Time.now}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    User.find_by(id: 1)
  end
end

app/controllers/somethings_controller.rb
class SomethingsController < ApplicationController
  before_action :set_something, only: [:show, :edit, :update, :destroy]

  # GET /somethings
  # GET /somethings.json
  def index
    @somethings = Something.all
  end

  # GET /somethings/1
  # GET /somethings/1.json
  def show
  end

  # GET /somethings/new
  def new
    @something = Something.new
  end

  # GET /somethings/1/edit
  def edit
  end

  # POST /somethings
  # POST /somethings.json
  def create
    @something = Something.new(something_params)

    respond_to do |format|
      if @something.save
        format.html { redirect_to @something, notice: 'Something was successfully created.' }
        format.json { render :show, status: :created, location: @something }
      else
        format.html { render :new }
        format.json { render json: @something.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /somethings/1
  # PATCH/PUT /somethings/1.json
  def update
    respond_to do |format|
      if @something.update(something_params)
        format.html { redirect_to @something, notice: 'Something was successfully updated.' }
        format.json { render :show, status: :ok, location: @something }
      else
        format.html { render :edit }
        format.json { render json: @something.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /somethings/1
  # DELETE /somethings/1.json
  def destroy
    @something.destroy
    respond_to do |format|
      format.html { redirect_to somethings_url, notice: 'Something was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /somethings/1/notify
  def notify
    WebNotificationsChannel.broadcast_to(
      current_user,
      title: 'New things!',
      body: 'All the news fit to print'
    )

    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_something
      @something = Something.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def something_params
      params.fetch(:something, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/somethings_helper.rb
module SomethingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Websockets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/somethings/_form.html.erb
<%= form_with(model: something, local: true) do |form| %>
  <% if something.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(something.errors.count, "error") %> prohibited this something from being saved:</h2>

      <ul>
        <% something.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/somethings/edit.html.erb
<h1>Editing Something</h1>

<%= render 'form', something: @something %>

<%= link_to 'Show', @something %> |
<%= link_to 'Back', somethings_path %>

app/views/somethings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Somethings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <td><%= link_to 'Notify', something_notify_path(something_id: 1) %></td>
  </tbody>
</table>

<br>

<%= link_to 'New Something', new_something_path %>

app/views/somethings/new.html.erb
<h1>New Something</h1>

<%= render 'form', something: @something %>

<%= link_to 'Back', somethings_path %>

app/views/somethings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_something_path(@something) %> |
<%= link_to 'Back', somethings_path %>